import { useEffect, useRef, useState } from "react";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import DashboardLayout from "@/components/dashboard-layout";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Sparkles,
  Loader2,
  ArrowRight,
  ArrowLeft,
  AlertTriangle,
  ShieldAlert,
  Bookmark,
} from "lucide-react";

interface AdvisorPick {
  symbol: string;
  companyName: string;
  action: "BUY" | "WATCH" | "AVOID";
  suggestedBuyZoneLow: number;
  suggestedBuyZoneHigh: number;
  targetPrice: number;
  stopLoss: number;
  timeHorizon: string;
  confidence: "Low" | "Medium" | "High";
  triggeringStrategies: string[];
  rationale: string;
}

interface AdvisorResult {
  generatedAt: string;
  disclaimer: string;
  picks: AdvisorPick[];
  note?: string;
}

const DISCLAIMER =
  "Educational analysis generated by AI from historical/technical signals. Not investment advice. Markets carry risk. Consult a SEBI-registered advisor before investing.";

function ActionBadge({ action }: { action: AdvisorPick["action"] }) {
  if (action === "BUY")
    return <Badge className="bg-green-600 text-white border-green-600">BUY</Badge>;
  if (action === "AVOID")
    return <Badge className="bg-[hsl(var(--accent))] text-white border-[hsl(var(--accent))]">AVOID</Badge>;
  return <Badge variant="outline">WATCH</Badge>;
}

export default function AdvisorPage() {
  const { toast } = useToast();
  const [isRunning, setIsRunning] = useState(false);
  const [progress, setProgress] = useState<{ percent: number; processed: number; total: number } | null>(null);
  const [result, setResult] = useState<AdvisorResult | null>(null);
  const [selected, setSelected] = useState<AdvisorPick | null>(null);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    return () => {
      if (pollRef.current) clearInterval(pollRef.current);
    };
  }, []);

  async function runAnalysis() {
    setIsRunning(true);
    setSelected(null);
    setProgress({ percent: 0, processed: 0, total: 4 });
    try {
      await apiRequest("POST", "/api/advisor/analyze");

      await new Promise<void>((resolve, reject) => {
        if (pollRef.current) clearInterval(pollRef.current);
        pollRef.current = setInterval(async () => {
          try {
            const job = await fetch("/api/status/ai-analyst").then((r) => r.json());
            setProgress({ percent: job.percent ?? 0, processed: job.processed ?? 0, total: job.total ?? 4 });
            if (job.stage === "complete") {
              if (pollRef.current) clearInterval(pollRef.current);
              setResult(job.result);
              resolve();
            } else if (job.stage === "error") {
              if (pollRef.current) clearInterval(pollRef.current);
              reject(new Error(job.message || "Analysis failed"));
            }
          } catch {
            // transient polling hiccup — keep trying
          }
        }, 1500);
      });
    } catch (error: any) {
      toast({ title: "Analysis failed", description: error.message, variant: "destructive" });
    } finally {
      setIsRunning(false);
      setProgress(null);
    }
  }

  async function saveAnalysis() {
    if (!result) return;
    try {
      await apiRequest("POST", "/api/advisor/saved", {
        generatedAt: result.generatedAt,
        picks: result.picks,
      });
      toast({ title: "Saved", description: "Analysis saved to your account." });
    } catch (error: any) {
      toast({ title: "Could not save", description: error.message, variant: "destructive" });
    }
  }

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Masthead */}
        <div className="border-b-4 border-foreground pb-4">
          <div className="news-label mb-2">Editor&rsquo;s Analysis &middot; New Here? Start Here</div>
          <h1 className="font-serif text-3xl sm:text-4xl font-black tracking-tight" data-testid="text-advisor-heading">
            The AI Analyst
          </h1>
          <p className="font-body text-sm sm:text-base text-neutral-600 mt-2 max-w-2xl">
            Don&rsquo;t know where to start? Let the AI Analyst read today&rsquo;s signals across every
            strategy on the desk and explain, in plain language, which stocks look interesting right now
            &mdash; and why.
          </p>
        </div>

        {!selected && (
          <>
            {/* Run button / progress */}
            <div className="border border-foreground bg-card p-6 sm:p-8 text-center">
              {!isRunning && !result && (
                <>
                  <Sparkles className="w-8 h-8 mx-auto mb-3" strokeWidth={1.5} />
                  <p className="font-body text-sm text-neutral-600 mb-5 max-w-md mx-auto">
                    One click reviews the latest signals from all strategies, checks live indicators, and
                    writes a short, jargon-free shortlist.
                  </p>
                  <Button size="lg" onClick={runAnalysis} data-testid="button-run-analysis">
                    Analyze Today&rsquo;s Market <ArrowRight className="w-4 h-4 ml-1" />
                  </Button>
                </>
              )}
              {isRunning && progress && (
                <div className="max-w-sm mx-auto">
                  <div className="flex items-center justify-center gap-2 text-sm font-medium mb-3">
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Reading the market&hellip;
                  </div>
                  <Progress value={progress.percent} className="h-2" />
                  <p className="news-label mt-2">
                    Step {progress.processed} / {progress.total}
                  </p>
                </div>
              )}
              {!isRunning && result && (
                <Button variant="outline" onClick={runAnalysis} data-testid="button-rerun-analysis">
                  <Sparkles className="w-4 h-4 mr-2" /> Run Again
                </Button>
              )}
            </div>

            {/* Disclaimer — always visible on this section */}
            <div className="border border-[hsl(var(--accent))] bg-[hsl(var(--accent))]/5 p-4 flex items-start gap-3">
              <ShieldAlert className="w-4 h-4 text-[hsl(var(--accent))] shrink-0 mt-0.5" />
              <p className="font-body text-xs sm:text-sm text-neutral-700">{DISCLAIMER}</p>
            </div>

            {/* Results */}
            {result && (
              <div>
                <div className="flex items-center justify-between mb-3">
                  <div className="news-label">
                    Editor&rsquo;s Picks &middot; Generated {new Date(result.generatedAt).toLocaleString()}
                  </div>
                  {result.picks.length > 0 && (
                    <button
                      onClick={saveAnalysis}
                      className="news-label hover:text-foreground inline-flex items-center gap-1"
                      data-testid="button-save-analysis"
                    >
                      <Bookmark className="w-3 h-3" /> Save
                    </button>
                  )}
                </div>

                {result.note && (
                  <div className="border border-foreground/30 bg-secondary p-4 mb-4 flex items-start gap-3">
                    <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
                    <p className="font-body text-sm text-neutral-700">{result.note}</p>
                  </div>
                )}

                {result.picks.length > 0 && (
                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 border-t border-l border-foreground">
                    {result.picks.map((pick, i) => (
                      <button
                        key={pick.symbol}
                        onClick={() => setSelected(pick)}
                        data-testid={`card-pick-${i}`}
                        className="group text-left border-r border-b border-foreground p-5 cursor-pointer transition-colors hover:bg-foreground hover:text-background"
                      >
                        <div className="flex items-start justify-between mb-3">
                          <span className="font-mono text-3xl font-bold leading-none text-foreground/15 group-hover:text-[hsl(var(--accent))]">
                            {String(i + 1).padStart(2, "0")}
                          </span>
                          <ActionBadge action={pick.action} />
                        </div>
                        <h3 className="font-serif text-lg font-bold leading-tight">{pick.symbol.replace(".NS", "")}</h3>
                        <p className="font-body text-xs text-neutral-600 group-hover:text-background/75 mb-3 truncate">
                          {pick.companyName}
                        </p>
                        <div className="grid grid-cols-2 gap-2 text-xs font-mono mb-3">
                          <div>
                            <div className="opacity-60">Buy Zone</div>
                            <div className="font-semibold">₹{pick.suggestedBuyZoneLow}&ndash;{pick.suggestedBuyZoneHigh}</div>
                          </div>
                          <div>
                            <div className="opacity-60">Target</div>
                            <div className="font-semibold">₹{pick.targetPrice}</div>
                          </div>
                        </div>
                        <div className="flex items-center justify-between news-label">
                          <span>{pick.timeHorizon}</span>
                          <span>{pick.confidence} confidence</span>
                        </div>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            )}
          </>
        )}

        {/* Detail view — "Why this stock?" */}
        {selected && (
          <div>
            <button
              onClick={() => setSelected(null)}
              className="news-label hover:text-foreground inline-flex items-center gap-1 mb-4"
              data-testid="button-back-to-picks"
            >
              <ArrowLeft className="w-3 h-3" /> Back to Editor&rsquo;s Picks
            </button>

            <div className="border border-foreground bg-card">
              <div className="border-b-4 border-foreground p-6 flex items-start justify-between gap-4">
                <div>
                  <div className="news-label mb-1">{selected.companyName}</div>
                  <h2 className="font-serif text-3xl font-black tracking-tight">{selected.symbol.replace(".NS", "")}</h2>
                </div>
                <ActionBadge action={selected.action} />
              </div>

              <div className="p-6 grid grid-cols-2 sm:grid-cols-4 border-b border-foreground/20">
                {[
                  { label: "Buy Zone", value: `₹${selected.suggestedBuyZoneLow}–${selected.suggestedBuyZoneHigh}` },
                  { label: "Target", value: `₹${selected.targetPrice}` },
                  { label: "Stop Loss", value: `₹${selected.stopLoss}` },
                  { label: "Horizon", value: selected.timeHorizon },
                ].map((stat) => (
                  <div key={stat.label} className="p-2">
                    <div className="news-label mb-1">{stat.label}</div>
                    <div className="font-mono text-lg font-bold">{stat.value}</div>
                  </div>
                ))}
              </div>

              <div className="p-6 border-b border-foreground/20">
                <div className="news-label mb-2">Why This Stock?</div>
                <p className="font-body text-base leading-relaxed text-neutral-700">{selected.rationale}</p>
              </div>

              <div className="p-6 border-b border-foreground/20">
                <div className="news-label mb-3">Flagged By {selected.triggeringStrategies.length} Strateg{selected.triggeringStrategies.length === 1 ? "y" : "ies"}</div>
                <div className="flex flex-wrap gap-2">
                  {selected.triggeringStrategies.map((s) => (
                    <Badge key={s} variant="outline">{s}</Badge>
                  ))}
                </div>
              </div>

              <div className="p-6 flex items-start gap-3 bg-secondary">
                <ShieldAlert className="w-4 h-4 shrink-0 mt-0.5" />
                <p className="font-body text-xs text-neutral-700">{DISCLAIMER}</p>
              </div>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
