import { useQuery } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import DashboardLayout from "@/components/dashboard-layout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Bookmark, Trash2, ShieldAlert } from "lucide-react";

interface SavedAnalysis {
  id: string;
  generatedAt: string;
  createdAt: string;
  picks: Array<{
    symbol: string;
    companyName: string;
    action: "BUY" | "WATCH" | "AVOID";
    suggestedBuyZoneLow: number;
    suggestedBuyZoneHigh: number;
    targetPrice: number;
    stopLoss: number;
    timeHorizon: string;
    confidence: "Low" | "Medium" | "High";
    triggeringStrategies: string[];
    rationale: string;
  }>;
}

function ActionBadge({ action }: { action: string }) {
  if (action === "BUY")
    return <Badge className="bg-green-600 text-white border-green-600">BUY</Badge>;
  if (action === "AVOID")
    return <Badge className="bg-[hsl(var(--accent))] text-white border-[hsl(var(--accent))]">AVOID</Badge>;
  return <Badge variant="outline">WATCH</Badge>;
}

export default function SavedPage() {
  const { toast } = useToast();

  const { data: savedItems = [], isLoading } = useQuery<SavedAnalysis[]>({
    queryKey: ["/api/advisor/saved"],
    queryFn: async () => {
      const res = await fetch("/api/advisor/saved", { credentials: "include" });
      if (!res.ok) return [];
      return res.json();
    },
  });

  async function deleteSaved(id: string) {
    try {
      await apiRequest("DELETE", `/api/advisor/saved/${id}`);
      queryClient.invalidateQueries({ queryKey: ["/api/advisor/saved"] });
      toast({ title: "Removed", description: "Saved pick removed." });
    } catch (err: any) {
      toast({ title: "Error", description: err.message, variant: "destructive" });
    }
  }

  // Flatten all saved analyses into individual stock picks for a stock-wise view.
  const allPicks = savedItems.flatMap((analysis) =>
    analysis.picks.map((pick) => ({
      ...pick,
      analysisId: analysis.id,
      savedAt: analysis.createdAt,
      generatedAt: analysis.generatedAt,
    })),
  );

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Masthead */}
        <div className="border-b-4 border-foreground pb-4">
          <div className="news-label mb-2">Your Collection &middot; Stock-by-Stock</div>
          <h1 className="font-serif text-3xl sm:text-4xl font-black tracking-tight" data-testid="text-saved-heading">
            Saved Picks
          </h1>
          <p className="font-body text-sm text-neutral-600 mt-2 max-w-2xl">
            Stocks you bookmarked from the AI Analyst. Each one includes the full reasoning and the
            strategies that flagged it — review them anytime.
          </p>
        </div>

        {/* Disclaimer */}
        <div className="border border-foreground/30 bg-secondary p-4 flex items-start gap-3">
          <ShieldAlert className="w-4 h-4 shrink-0 mt-0.5" />
          <p className="font-body text-xs text-neutral-700">
            These picks were generated by AI from historical/technical signals at the time they were saved.
            Markets change — always verify current data before making decisions. Not investment advice.
          </p>
        </div>

        {isLoading && (
          <div className="text-center py-12 text-muted-foreground text-sm">Loading saved picks…</div>
        )}

        {!isLoading && allPicks.length === 0 && (
          <div className="border border-foreground bg-card p-10 text-center">
            <Bookmark className="w-8 h-8 mx-auto mb-3 text-muted-foreground" strokeWidth={1.5} />
            <p className="font-body text-sm text-neutral-600 mb-2">No saved picks yet.</p>
            <p className="news-label">
              Go to The AI Analyst → hover a stock card → click the bookmark icon to save it here.
            </p>
          </div>
        )}

        {allPicks.length > 0 && (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 border-t border-l border-foreground">
            {allPicks.map((pick, i) => (
              <div
                key={`${pick.analysisId}-${pick.symbol}-${i}`}
                className="border-r border-b border-foreground p-5"
              >
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <h3 className="font-serif text-lg font-bold leading-tight">
                      {pick.symbol.replace(".NS", "")}
                    </h3>
                    <p className="font-body text-xs text-neutral-600 truncate">{pick.companyName}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <ActionBadge action={pick.action} />
                    <button
                      onClick={() => deleteSaved(pick.analysisId)}
                      className="p-1 hover:text-[hsl(var(--accent))] transition-colors"
                      title="Remove from saved"
                      aria-label={`Remove ${pick.symbol}`}
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-2 text-xs font-mono mb-3">
                  <div>
                    <div className="news-label text-[0.55rem]">Buy Zone</div>
                    <div className="font-semibold">₹{pick.suggestedBuyZoneLow}–{pick.suggestedBuyZoneHigh}</div>
                  </div>
                  <div>
                    <div className="news-label text-[0.55rem]">Target</div>
                    <div className="font-semibold">₹{pick.targetPrice}</div>
                  </div>
                  <div>
                    <div className="news-label text-[0.55rem]">Stop Loss</div>
                    <div className="font-semibold">₹{pick.stopLoss}</div>
                  </div>
                  <div>
                    <div className="news-label text-[0.55rem]">Horizon</div>
                    <div className="font-semibold">{pick.timeHorizon}</div>
                  </div>
                </div>

                <p className="font-body text-xs leading-relaxed text-neutral-700 mb-3">{pick.rationale}</p>

                <div className="flex flex-wrap gap-1 mb-2">
                  {pick.triggeringStrategies.map((s) => (
                    <Badge key={s} variant="outline" className="text-[0.6rem]">{s}</Badge>
                  ))}
                </div>

                <div className="news-label text-[0.5rem]">
                  {pick.confidence} confidence &middot; Saved {new Date(pick.savedAt).toLocaleDateString()}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
